[package]
name = "probly-search-demo"
description = "A Github pages wasm demo"
version = "0.1.0"
authors = ["marcus-pousette <marcus.pousette@quantleaf.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
probly-search = "1.0.0"
wasm-bindgen = "0.2"